#!/usr/bin/bash

PIDS_PATH="/var/run/strait"

if [ ! -d $PIDS_PATH ]; then
  mkdir -m 755 $SUDO_USER $PIDS_PATH && chown $SUDO_USER. $PIDS_PATH
  echo "create $PIDS_PATH"
  echo "ok"
else
  echo "nothing to do..."
fi
